# build-tools.sh installs vim, tmux and tmux-mem-cpu-load into ~/.local
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
export PATH=$HOME/llvm-project/install/bin:$PATH
export PATH=$HOME/.docker/bin:$PATH
export PATH=$HOME/.opencode/bin:$PATH

# oh-my-zsh (https://github.com/ohmyzsh/ohmyzsh/wiki/Themes)
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Sourced after oh-my-zsh so these aliases take precedence over its own.
source $HOME/.shrc

source <(fzf --zsh)

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
