[General]
  snippetfile = "/home/jamieh/.config/pet/snippet.toml"
  editor = "vim"
  column = 40
  selectcmd = "fzf"
  sortby = "description"

[Gist]
  file_name = "pet-snippet.toml"
  access_token = ""
  gist_id = ""
  public = false
